@echo off
setlocal enabledelayedexpansion
set "TARGETDIR=%LOCALAPPDATA%\shadow578\EphemeralSessionBrowser"
set "TARGET=%TARGETDIR%\EphemeralSessionBrowser.ps1"
set SKIP=20
del "%TARGET%"
if not exist "%TARGET%" (
  mkdir "%TARGETDIR%"
  set i=0
  > "%TARGET%" (
    for /f "usebackq delims=" %%A in ("%~f0") do (
      set /a i+=1
      if !i! gtr %SKIP% echo(%%A)
    )
  )
)
powershell.exe -NoProfile -ExecutionPolicy Bypass -File %TARGET% -Install
goto :EOF
exit
# --- end of installer bootstrapper ---

param(
  [switch]
  $Install
)

function Get-ChromePath([switch] $AllowNull)
{
  $cmd = Get-Command "chrome.exe"
  if ($null -eq $cmd) {
    if ($AllowNull) {
      Write-Host "Chrome executable not found, returning null."
      return $null
    }

    throw "Chrome executable not found! Please ensure that Google Chrome is installed and available in your PATH."
  }
  
  Write-Host "Using Chrome executable Version $($cmd.Version) at $($cmd.Source)"
  return $cmd.Source
}

#region Installer

function Install-Chrome()
{
  $chromePath = Get-ChromePath -AllowNull
  if ($null -eq $chromePath) {
    Write-Host "Chrome is not installed. Attempting to install via winget."
    winget install Google.Chrome
  }

  $chromePath = Get-ChromePath -AllowNull
  if ($null -eq $chromePath) {
    Write-Host "Chrome installation failed. Please install Google Chrome manually and rerun the script."
    throw "Chrome installation failed!"
  }
}

function New-Shortcut([string] $Path, [string] $Target, [string] $Description = "", [string] $IconLocation = "") {
  $wsh = New-Object -ComObject WScript.Shell
  $shortcut = $wsh.CreateShortcut($Path)
  $shortcut.TargetPath = $Target

  if ($Description) {
    $shortcut.Description = $Description
  }

  if ($IconLocation) {
    $shortcut.IconLocation = $IconLocation
  }
  
  $shortcut.Save()
}

function Install() {
  Write-Host "Installing EphemeralSessionBrowser..."

  # ESP loads via a loader script, so create that
  $loaderPath = Join-Path -Path $PSScriptRoot -ChildPath "EphemeralSessionBrowser.loader.bat"
  $loader = @"
@echo off
powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "$PSCommandPath"
"@

  Remove-Item -Path $loaderPath -ErrorAction SilentlyContinue 

  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllLines($loaderPath, $loader, $utf8NoBom)

  # create desktop shortcut
  $desktopPath = [System.Environment]::GetFolderPath("Desktop")
  $desktopShortcutPath = Join-Path -Path $desktopPath -ChildPath "EphemeralSessionBrowser.lnk"
  Remove-Item $desktopShortcutPath -ErrorAction SilentlyContinue
  New-Shortcut -Path $desktopShortcutPath -Target $loaderPath -Description "Ephemeral Session Browser" -IconLocation "$(Get-ChromePath),4"

  # chrome is required, so attempt install
  Install-Chrome

  # initial run
  Start-Process -FilePath $loaderPath
}

#endregion

#region Browser

$ProfilesPath = Join-Path -Path $PSScriptRoot -ChildPath "profiles"
$BaseProfilePath = Join-Path -Path $ProfilesPath -ChildPath "base"

function Get-RandomRGB() {
  # generate a random HSL color hue, with fixed saturation and lightness
  $h = Get-Random -Minimum 0 -Maximum 360
  $s = Get-Random -Minimum 0.33 -Maximum 0.66
  $l = Get-Random -Minimum 0.33 -Maximum 0.66

  # HSL to RGB conversion
  $c = (1 - [math]::Abs(2 * $l - 1)) * $s
  $x = $c * (1 - [math]::Abs(($h / 60) % 2 - 1))
  $m = $l - $c / 2

  switch ($h) {
    { $_ -lt 60 } { $r1 = $c; $g1 = $x; $b1 = 0; break }
    { $_ -lt 120 } { $r1 = $x; $g1 = $c; $b1 = 0; break }
    { $_ -lt 180 } { $r1 = 0; $g1 = $c; $b1 = $x; break }
    { $_ -lt 240 } { $r1 = 0; $g1 = $x; $b1 = $c; break }
    { $_ -lt 300 } { $r1 = $x; $g1 = 0; $b1 = $c; break }
    default { $r1 = $c; $g1 = 0; $b1 = $x }
  }

  $r = [math]::Round(255 * ($r1 + $m))
  $g = [math]::Round(255 * ($g1 + $m))
  $b = [math]::Round(255 * ($b1 + $m))

  return "$r,$g,$b"
}

function Start-Browser([string] $ProfilePath, [bool] $IsBaseProfile) {
  $themeRGB = "255,255,255"
  if (-not $IsBaseProfile) {
    $themeRGB = Get-RandomRGB
  }

  Write-Host "starting chrome with profile at $ProfilePath, theme = $themeRGB, isBaseProfile = $IsBaseProfile"
  return Start-Process -FilePath "$(Get-ChromePath)" -ArgumentList @(
    "--user-data-dir=`"$ProfilePath`"",
    "--install-autogenerated-theme=`"$themeRGB`""
  ) -PassThru
}

function New-EphemeralProfileName() {
  $profileName = "tmp$(Get-Random -Minimum 1000 -Maximum 9999)"
  return $profileName
}

function Get-EphemeralProfilePath([string] $Name, [bool] $CreateIfNotExists) {
  $tmpProfilePath = Join-Path -Path $ProfilesPath -ChildPath $Name

  if ($CreateIfNotExists -and -not (Test-Path -Path $tmpProfilePath)) {
    Write-Host "profile path $tmpProfilePath does not exist, creating it now"
    New-EphemeralProfile -Name $Name
  }

  return $tmpProfilePath
}

function New-EphemeralProfile([string] $Name) {
  $tmpProfilePath = Get-EphemeralProfilePath $Name -CreateIfNotExists:$false

  Write-Host "preparing temporary profile at $tmpProfilePath"
  Remove-Item -Path $tmpProfilePath -Recurse -Force -ErrorAction SilentlyContinue
  Copy-Item -Path $BaseProfilePath -Destination $tmpProfilePath -Recurse -Force
}

function Remove-EphemeralProfile([string] $Name) {
  $tmpProfilePath = Get-EphemeralProfilePath $Name -CreateIfNotExists:$false

  Write-Host "removing temporary profile at $tmpProfilePath"
  Remove-Item -Path $tmpProfilePath -Recurse -Force -ErrorAction SilentlyContinue
}

function Set-CachedProfileName([string] $Name) {
  $cachedProfilePath = Join-Path -Path $ProfilesPath -ChildPath "cached.txt"
  if (-not (Test-Path -Path $ProfilesPath)) {
    New-Item -ItemType Directory -Path $ProfilesPath -Force
  }
  Set-Content -Path $cachedProfilePath -Value $Name
  Write-Host "cached profile name set to $Name"
}

function Get-CachedProfileName() {
  $cachedProfilePath = Join-Path -Path $ProfilesPath -ChildPath "cached.txt"
  if (Test-Path -Path $cachedProfilePath) {
    return Get-Content -Path $cachedProfilePath
  }
  return $null
}

function Test-ShiftKeyPressedAsync() {
  Add-Type @"
using System;
using System.Runtime.InteropServices;

public static class KeyHelper
{
  [DllImport("user32.dll")]
  static extern short GetAsyncKeyState(int vKey);

  public static bool IsKeyPressed(int keyCode)
  {
    // note: ^!= is required here since loader will otherwise mangle the expression
    return (GetAsyncKeyState(keyCode) & 0x8000) ^!= 0; 
  }
}
"@

  return [KeyHelper]::IsKeyPressed(0x10) # 0x10 == VK_SHIFT
}

function Show-BaseProfileInfoMessage($FirstRun) {
  try {
    $commonBody = @"
Any changes made to this profile will be saved and used for future sessions.
<br>
To save changes, simply close the browser window.
To access the base profile at a later time, press SHIFT while launching the Ephemeral Session Browser.
"@

    if ($FirstRun) {
      $title = "Welcome to the Ephemeral Session Browser"
      $body = @"
Welcome to the Ephemeral Session Browser!
<br>
Since this is the first time you're starting the browser, it started in the base profile.
$commonBody
"@
    }
    else {
      $title = "Ephemeral Session Browser"
      $body = @"
The Ephemeral Session Browser has started in the base profile upon your request.
$commonBody
"@
    }

    # loader mangles empty lines
    $body = $body -replace "<br>", "`n" 

    Add-Type -AssemblyName System.Windows.Forms
    [System.Windows.Forms.MessageBox]::Show($body, $title, [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information)
  }
  catch {
    Write-Host "failed to show message box: $_"
  }
}

function Start-EphemeralBrowser() {
  if (-not (Test-Path -Path $ProfilesPath)) {
    New-Item -ItemType Directory -Path $ProfilesPath -Force
  }

  $firstRun = -not (Test-Path -Path $BaseProfilePath)
  $shiftPressed = Test-ShiftKeyPressedAsync
  if ($firstRun -or $shiftPressed) {
    Write-Host "starting chrome with base profile at $BaseProfilePath (first run: $firstRun, shift pressed: $shiftPressed)"
    $browser = Start-Browser -ProfilePath $BaseProfilePath -IsBaseProfile $true

    Show-BaseProfileInfoMessage -FirstRun $firstRun

    $browser.WaitForExit()

    Write-Host "recreating cached profile after editing base profile"
    $cachedProfileName = Get-CachedProfileName
    if ($null -ne $cachedProfileName) {
      Remove-EphemeralProfile -Name $cachedProfileName
    }
    $cachedProfileName = New-EphemeralProfileName
    New-EphemeralProfile -Name $cachedProfileName
    Set-CachedProfileName -Name $cachedProfileName
  }
  else {
    $cachedProfileName = Get-CachedProfileName
    if ($null -eq $cachedProfileName) {
      Write-Host "no cached profile name found, creating profile on-demand"
      $cachedProfileName = New-EphemeralProfileName
      New-EphemeralProfile -Name $cachedProfileName
    }

    $profilePath = Get-EphemeralProfilePath -Name $cachedProfileName -CreateIfNotExists:$true
    $browser = Start-Browser -ProfilePath $profilePath -IsBaseProfile $false

    $nextProfileName = New-EphemeralProfileName
    New-EphemeralProfile -Name $nextProfileName
    Set-CachedProfileName -Name $nextProfileName

    $browser.WaitForExit()

    Remove-EphemeralProfile -Name $cachedProfileName
  }
}

#endregion

function Main() {
  if ($Install) {
    Install
    return
  }

  Start-EphemeralBrowser
}
Main
