param(
    [switch]
    $BaseProfile,

    [string]
    $ProfilesPath = "$env:LOCALAPPDATA\MSB\Profiles\"
)

$BaseProfilePath = Join-Path -Path $ProfilesPath -ChildPath "base"

function Get-RandomRGB()
{
    # generate a random HSL color hue, with fixed saturation and lightness
    $h = Get-Random -Minimum 0 -Maximum 360
    $s = Get-Random -Minimum 0.33 -Maximum 0.66
    $l = Get-Random -Minimum 0.33 -Maximum 0.66

    # HSL to RGB conversion
    $c = (1 - [math]::Abs(2 * $l - 1)) * $s
    $x = $c * (1 - [math]::Abs(($h / 60) % 2 - 1))
    $m = $l - $c / 2

    switch ($h) {
        {$_ -lt 60}   { $r1 = $c; $g1 = $x; $b1 = 0; break }
        {$_ -lt 120}  { $r1 = $x; $g1 = $c; $b1 = 0; break }
        {$_ -lt 180}  { $r1 = 0; $g1 = $c; $b1 = $x; break }
        {$_ -lt 240}  { $r1 = 0; $g1 = $x; $b1 = $c; break }
        {$_ -lt 300}  { $r1 = $x; $g1 = 0; $b1 = $c; break }
        default       { $r1 = $c; $g1 = 0; $b1 = $x }
    }

    $r = [math]::Round(255 * ($r1 + $m))
    $g = [math]::Round(255 * ($g1 + $m))
    $b = [math]::Round(255 * ($b1 + $m))

    return "$r,$g,$b"
}

function Start-Browser([string] $ProfilePath, [bool] $IsBaseProfile)
{
    $themeRGB = "255,255,255"
    if (-not $IsBaseProfile)
    {
        $themeRGB = Get-RandomRGB
    }

    Write-Host "starting chrome with profile at $ProfilePath, theme = $themeRGB, isBaseProfile = $IsBaseProfile"
    return Start-Process -FilePath "chrome.exe" -ArgumentList @(
        "--user-data-dir=`"$ProfilePath`"",
        "--install-autogenerated-theme=`"$themeRGB`""
    ) -PassThru
}

function New-EphemeralProfileName()
{
    $profileName = "tmp$(Get-Random -Minimum 1000 -Maximum 9999)"
    return $profileName
}

function Get-EphemeralProfilePath([string] $Name, [bool] $CreateIfNotExists)
{
    $tmpProfilePath = Join-Path -Path $ProfilesPath -ChildPath $Name

    if ($CreateIfNotExists -and -not (Test-Path -Path $tmpProfilePath))
    {
        Write-Host "profile path $tmpProfilePath does not exist, creating it now"
        New-EphemeralProfile -Name $Name
    }

    return $tmpProfilePath
}

function New-EphemeralProfile([string] $Name)
{
    $tmpProfilePath = Get-EphemeralProfilePath $Name -CreateIfNotExists:$false

    Write-Host "preparing temporary profile at $tmpProfilePath"
    Remove-Item -Path $tmpProfilePath -Recurse -Force -ErrorAction SilentlyContinue
    Copy-Item -Path $BaseProfilePath -Destination $tmpProfilePath -Recurse -Force
}

function Remove-EphemeralProfile([string] $Name)
{
    $tmpProfilePath = Get-EphemeralProfilePath $Name -CreateIfNotExists:$false

    Write-Host "removing temporary profile at $tmpProfilePath"
    Remove-Item -Path $tmpProfilePath -Recurse -Force -ErrorAction SilentlyContinue
}

function Set-CachedProfileName([string] $Name)
{
    $cachedProfilePath = Join-Path -Path $ProfilesPath -ChildPath "cached.txt"
    if (-not (Test-Path -Path $ProfilesPath))
    {
        New-Item -ItemType Directory -Path $ProfilesPath -Force
    }
    Set-Content -Path $cachedProfilePath -Value $Name
    Write-Host "cached profile name set to $Name"
}

function Get-CachedProfileName()
{
    $cachedProfilePath = Join-Path -Path $ProfilesPath -ChildPath "cached.txt"
    if (Test-Path -Path $cachedProfilePath)
    {
        return Get-Content -Path $cachedProfilePath
    }
    return $null
}

function Main()
{
    if (-not (Test-Path -Path $ProfilesPath))
    {
        New-Item -ItemType Directory -Path $ProfilesPath -Force
    }

    if ($BaseProfile)
    {
        Write-Host "starting chrome with base profile at $BaseProfilePath"
        $browser = Start-Browser -ProfilePath $BaseProfilePath -IsBaseProfile $true
        $browser.WaitForExit()

        Write-Host "recreating cached profile after editing base profile"
        $cachedProfileName = Get-CachedProfileName
        if ($null -ne $cachedProfileName)
        {
            Remove-EphemeralProfile -Name $cachedProfileName
        }
        $cachedProfileName = New-EphemeralProfileName
        New-EphemeralProfile -Name $cachedProfileName
        Set-CachedProfileName -Name $cachedProfileName
    }
    else
    {
        $cachedProfileName = Get-CachedProfileName
        if ($null -eq $cachedProfileName)
        {
            Write-Host "no cached profile name found, creating profile on-demand"
            $cachedProfileName = New-EphemeralProfileName
            New-EphemeralProfile -Name $cachedProfileName
        }

        $profilePath = Get-EphemeralProfilePath -Name $cachedProfileName -CreateIfNotExists:$true
        $browser = Start-Browser -ProfilePath $profilePath -IsBaseProfile $false

        $nextProfileName = New-EphemeralProfileName
        New-EphemeralProfile -Name $nextProfileName
        Set-CachedProfileName -Name $nextProfileName

        $browser.WaitForExit()

        Remove-EphemeralProfile -Name $cachedProfileName
    }
}

Main
